version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_tp
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: pokemon_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n
    container_name: n8n_tp
    restart: always
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_DATABASE: pokemon_db
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n
    depends_on:
      - postgres

  minio:
    image: minio/minio
    container_name: minio_tp
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  metabase:
    image: metabase/metabase:latest
    container_name: metabase_tp
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  pgdata:
  minio_data: